### ISSUE TITLE
Trains from outside of claims, explode when disassembled inside a claim.

### ISSUE THREAD

**Issue by Atakku** [thexaero/opac-fabric-create-support#4]
Would have been bearable if chests dropped their contents, but they don't which makes the situation require rollback for me.
Would make much more sense to refuse disassembly.

**Comment by thexaero** [comment]
Chests not dropping contents is on Create's end. Would do the same if a chest was disassembled into bedrock.
I don't think there was a good way to refuse disassembly with a code injection. I probably would've done it otherwise. The claims are just considered indestructible like bedrock.
You should assemble them in a compatible claim (e.g. the same sub-claim), if you don't them to break on disassembly.
